version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: _docker/Dockerfile.server
    ports:
      - "80:8080"
    networks:
    - mg-backend
networks:
  mg-backend:
    driver: bridge
