version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: _docker/Dockerfile.test.server
    environment:
      - STATIC_ASSETS=/static
    ports:
      - "80:8080"
    networks:
    - mg-backend

  api:
    build:
      context: .
      dockerfile: _docker/Dockerfile.test.api
    ports:
      - "8080:8080"
    networks:
      - mg-backend

networks:
  mg-backend:
    driver: bridge
